# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='taveler',
            new_name='traveler',
        ),
    ]
