# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
        ('travel', '0002_auto_20170303_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='planner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trip_planner', to='login_reg.User'),
        ),
    ]
