# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
        ('travel', '0003_trip_planner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='planner',
        ),
        migrations.AddField(
            model_name='trip',
            name='planner',
            field=models.ManyToManyField(default=1, related_name='trip_planner', to='login_reg.User'),
        ),
    ]
